name: Integration

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  ping:
    runs-on: ubuntu-latest
    name: Trigger slack webhook

    steps:
      - name: Trigger slack webhook
        run: |
          TEXT=$(cat <<'EOF'
          :pr: New pull request on shopify/tapioca

          ${{ github.event.pull_request.html_url }}

          :buildkite: ${{ secrets.BUILDKITE_TRIGGER_URL }}?message=shopify/tapioca/${{ github.event.pull_request.number }}&branch=at-fix-tapioca-pipeline&env=TAPIOCA_REPO=${{ github.event.pull_request.head.repo.full_name }}%0ATAPIOCA_BRANCH=${{ github.event.pull_request.head.ref }}%0ATAPIOCA_PR=${{ github.event.pull_request.number }}#new
          EOF
          )

          curl -X POST -H 'Content-type: application/json' --fail ${{ secrets.SLACK_WEBHOOK_URL }} --data '{ "text": "$TEXT" }'
