# This is a basic workflow to help you get started with Actions

name: Ping

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ping:
    runs-on: ubuntu-latest
    name: Trigger slack webhook

    steps:
      - name: Trigger slack webhook
        run: |
          curl -X POST -H 'Content-type: application/json' ${{ secrets.SLACK_WEBHOOK_URL }} --data \
          '
          {
            "pull_request_number": "${{ github.event.pull_request.number }}",
            "pull_request_title": "${{ github.event.pull_request.title }}",
            "pull_request_user": "${{ github.event.pull_request.user.login }}",
            "pull_request_repo": "${{ github.event.pull_request.base.repo.full_name }}",
            "pull_request_branch": "${{ github.event.pull_request.base.ref }}"
          }'
